using Billpay_lambda.Dtos;

namespace Billpay_lambda.Helpers;

public static class AtmHelper
{
    private static readonly List<AtmDto> atmList =
    [
        new AtmDto
        {
            Id = new Guid("03f7b867-3f3e-4fbb-961a-7fe4c9a9329f"),
            TermId = "T000000013",
            TermNo = "D0000003",
            Lat = 37.486,
            Lng = 127.1028,
            AgentId = "30014943",
            AgentSequence = "36",
            Location = "211-2 Suseo-dong, Gangnam District, Seoul, South Korea",
            PostalCd = null,
            WorkSunFlag = "1",
            WorkSunStartTime = "0000",
            WorkSunEndTime = "2359",
            WorkMonFlag = "1",
            WorkMonStartTime = "0000",
            WorkMonEndTime = "2359",
            WorkTueFlag = "1",
            WorkTueStartTime = "0000",
            WorkTueEndTime = "2359",
            WorkWebFlag = "1",
            WorkWebStartTime = "0000",
            WorkWebEndTime = "2359",
            WorkThuFlag = "1",
            WorkThuStartTime = "0000",
            WorkThuEndTime = "2359",
            WorkFriFlag = "1",
            WorkFriStartTime = "0000",
            WorkFriEndTime = "2359",
            WorkSatFlag = "1",
            WorkSatStartTime = "0000",
            WorkSatEndTime = "2359",
            PartnerCd = "2",
            AvailableTransaction = true,
            CancelCapability = true
        },
        new AtmDto
        {
            Id = new Guid("e8b6c62a-69b8-48c7-88f4-91f98272b694"),
            TermId = "T000000027",
            TermNo = "HQ0001",
            Lat = 37.4880028,
            Lng = 127.1026639,
            AgentId = null,
            AgentSequence = null,
            Location = "281 Gwangpyeong-ro, Gangnam-gu, Seoul",
            PostalCd = null,
            WorkSunFlag = "1",
            WorkSunStartTime = "0000",
            WorkSunEndTime = "2359",
            WorkMonFlag = "1",
            WorkMonStartTime = "0000",
            WorkMonEndTime = "2359",
            WorkTueFlag = "1",
            WorkTueStartTime = "0000",
            WorkTueEndTime = "2359",
            WorkWebFlag = "1",
            WorkWebStartTime = "0000",
            WorkWebEndTime = "2359",
            WorkThuFlag = "1",
            WorkThuStartTime = "0000",
            WorkThuEndTime = "2359",
            WorkFriFlag = "1",
            WorkFriStartTime = "0000",
            WorkFriEndTime = "2359",
            WorkSatFlag = "1",
            WorkSatStartTime = "0000",
            WorkSatEndTime = "2359",
            PartnerCd = "2",
            AvailableTransaction = true,
            CancelCapability = true
        },
        new AtmDto
        {
            Id = new Guid("0c6e6b27-77b1-4b3f-94c3-5d3a6e8c0fe5"),
            TermId = "T000000011",
            TermNo = "D0000002",
            Lat = 37.488456,
            Lng = 127.10419,
            AgentId = null,
            AgentSequence = null,
            Location = "South Korea, street address Seogwan-dong KR #1512, 716 Suseo-dong, Gangnam-gu, Seoul",
            PostalCd = null,
            WorkSunFlag = "1",
            WorkSunStartTime = "0000",
            WorkSunEndTime = "2359",
            WorkMonFlag = "1",
            WorkMonStartTime = "0000",
            WorkMonEndTime = "2359",
            WorkTueFlag = "1",
            WorkTueStartTime = "0000",
            WorkTueEndTime = "2359",
            WorkWebFlag = "1",
            WorkWebStartTime = "0000",
            WorkWebEndTime = "2359",
            WorkThuFlag = "1",
            WorkThuStartTime = "0000",
            WorkThuEndTime = "2359",
            WorkFriFlag = "1",
            WorkFriStartTime = "0000",
            WorkFriEndTime = "2359",
            WorkSatFlag = "1",
            WorkSatStartTime = "0000",
            WorkSatEndTime = "2359",
            PartnerCd = "2",
            AvailableTransaction = true,
            CancelCapability = false
        },
        new AtmDto
        {
            Id = new Guid("1354a199-69e8-4a7d-9b6a-6a434029b9cc"),
            TermId = "T000000036",
            TermNo = "JULIE_LAPTOP",
            Lat = 37.4889719,
            Lng = 127.1053398,
            AgentId = "40081681",
            AgentSequence = "20",
            Location = "52 Bamgogae-ro 1-gil, Gangnam District, Seoul, South Korea",
            PostalCd = null,
            WorkSunFlag = "1",
            WorkSunStartTime = "0000",
            WorkSunEndTime = "2359",
            WorkMonFlag = "1",
            WorkMonStartTime = "0000",
            WorkMonEndTime = "2359",
            WorkTueFlag = "1",
            WorkTueStartTime = "0000",
            WorkTueEndTime = "2359",
            WorkWebFlag = "1",
            WorkWebStartTime = "0000",
            WorkWebEndTime = "2359",
            WorkThuFlag = "1",
            WorkThuStartTime = "0000",
            WorkThuEndTime = "2359",
            WorkFriFlag = "1",
            WorkFriStartTime = "0000",
            WorkFriEndTime = "2359",
            WorkSatFlag = "1",
            WorkSatStartTime = "0000",
            WorkSatEndTime = "2359",
            PartnerCd = "2",
            AvailableTransaction = true,
            CancelCapability = true
        },
        new AtmDto
        {
            Id = new Guid("6b023e5b-06c5-4b1e-bc5d-6d46d0e3e3b6"),
            TermId = "T000000001",
            TermNo = "D0000001",
            Lat = 37.4982444,
            Lng = 127.1021918,
            AgentId = null,
            AgentSequence = null,
            Location = "909 Garak-dong, Songpa District, Seoul, South Korea",
            PostalCd = null,
            WorkSunFlag = "1",
            WorkSunStartTime = "0000",
            WorkSunEndTime = "2359",
            WorkMonFlag = "1",
            WorkMonStartTime = "0000",
            WorkMonEndTime = "2359",
            WorkTueFlag = "1",
            WorkTueStartTime = "0000",
            WorkTueEndTime = "2359",
            WorkWebFlag = "1",
            WorkWebStartTime = "0000",
            WorkWebEndTime = "2359",
            WorkThuFlag = "1",
            WorkThuStartTime = "0000",
            WorkThuEndTime = "2359",
            WorkFriFlag = "1",
            WorkFriStartTime = "0000",
            WorkFriEndTime = "2359",
            WorkSatFlag = "1",
            WorkSatStartTime = "0000",
            WorkSatEndTime = "2359",
            PartnerCd = "2",
            AvailableTransaction = true,
            CancelCapability = false
        }
    ];

    public static List<AtmDto> GetAllAtms()
    {
        return atmList;
    }
}
